library(psychometric)
library(readr)
data <- read_csv("ItemAnalysisAdult.csv")
item.exam(data[2:21], discrim = TRUE)
item.exam(data[23:42], discrim = TRUE)
item.exam(data[44:63], discrim = TRUE)

library(psychometric)
library(readr)
data <- read_csv("ItemAnalysisPrimary.csv")
item.exam(data[2:21], discrim = TRUE)
item.exam(data[23:42], discrim = TRUE)
item.exam(data[44:63], discrim = TRUE)

library(psychometric)
library(readr)
data <- read_csv("ItemAnalysisSecond.csv")
item.exam(data[2:21], discrim = TRUE)
item.exam(data[23:42], discrim = TRUE)
item.exam(data[44:63], discrim = TRUE)
