install.packages("MESS")
install.packages("vcdExtra")
library(vcdExtra)
library(MESS)
library(readr)
library(stats)
library(ggpubr)
library(effsize)
library(rstatix)
library(coin)
library(rcompanion)

data <- read_csv("PuzzTask_Adults.csv")

wilcox.test(data$avgPlan1, data$avgPlan2, paired = TRUE)
wilcox.test(data$avgSD1, data$avgSD2, paired = TRUE)
wilcox.test(data$RankDiff1, data$RankDiff2, paired = TRUE)
wilcox.test(data$Pred4Time, data$Pred9Time, paired = TRUE)
wilcox.test(data$AvgPredAcc1, data$AvgPredAcc2, paired = TRUE)

boxplot(data$avgPlan1, data$avgPlan2)
boxplot(data$avgSD1, data$avgSD2)
boxplot(data$RankDiff1, data$RankDiff2)
boxplot(data$Pred4Time, data$Pred9Time)
boxplot(data$AvgPredAcc1, data$AvgPredAcc2)

gkgamma(mytable)
GKgamma(mytable)

mytable <- table(data$avgPlanall, data$PuzzAcc)
mytable <- table(data$avgSDall, data$PuzzAcc)
mytable <- table(data$SAT, data$PuzzAcc)
mytable <- table(data$PredDiff, data$PuzzAcc)
mytable <- table(data$RankDiffall, data$PuzzAcc)
mytable <- table(data$AvgPredAcc, data$PuzzAcc)
mytable <- table(data$CJPuzzles, data$PuzzAcc)
mytable <- table(data$CJTime, data$AvgPredAcc)
mytable <- table(data$RefTimeAcc, data$PuzzAcc)
gkgamma(mytable)

mytable <- table(data$avgPlanall, data$avgSDall)
mytable <- table(data$avgPlanall, data$SAT)
mytable <- table(data$avgPlanall, data$RankDiffall)
mytable <- table(data$avgPlanall, data$AvgPredAcc)
mytable <- table(data$avgPlanall, data$RefPuzzAcc)
mytable <- table(data$avgPlanall, data$RefTimeAcc)
mytable <- table(data$avgSDall, data$SAT)
mytable <- table(data$avgSDall, data$RankDiffall)
mytable <- table(data$avgSDall, data$AvgPredAcc)
mytable <- table(data$avgSDall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$RefTimeAcc)
mytable <- table(data$SAT, data$RankDiffall)
mytable <- table(data$SAT, data$AvgPredAcc)
mytable <- table(data$SAT, data$RefPuzzAcc)
mytable <- table(data$SAT, data$RefTimeAcc)
mytable <- table(data$RankDiffall, data$AvgPredAcc)
mytable <- table(data$RankDiffall, data$RefPuzzAcc)
mytable <- table(data$RankDiffall, data$RefTimeAcc)
mytable <- table(data$AvgPredAcc, data$RefPuzzAcc)
mytable <- table(data$AvgPredAcc, data$RefTimeAcc)
mytable <- table(data$RefPuzzAcc, data$RefTimeAcc)
mytable <- table(data$avgPlan1, data$RankDiff1)
gkgamma(mytable)

anova <- aov(avgPlanall ~ Ceiling, data = data)
anova <- aov(avgSDall ~ Ceiling, data = data)
anova <- aov(RefPuzzAcc ~ Ceiling, data = data)
summary(anova)
TukeyHSD(anova)

ggscatter(data, x = "RefTimeAcc", y = "PuzzAcc", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Plan", ylab = "Achieve")

data <- read_csv("Qualitative_Adults.csv")

wilcox.test(data$PuzzAcc ~ data$atleastrsw, paired = FALSE)
wilcox_effsize(data, PuzzAcc ~ atleastrsw, paired = FALSE)
wilcox.test(data$RankAcc ~ data$GTD, paired = FALSE)
wilcox_effsize(data, RankAcc ~ GTD, paired = FALSE)
wilcox.test(data$PAAcc ~ data$atleastgf, paired = FALSE)
wilcox_effsize(data, PAAcc ~ atleastgf, paired = FALSE)
wilcox.test(data$PAAcc ~ data$feedback, paired = FALSE)
wilcox_effsize(data, PAAcc ~ feedback, paired = FALSE)
cor.test(data$StratNo, data$PuzzAcc, method = "spearman")
cor.test(data$StratNo, data$PAAcc, method = "spearman")
wilcox.test(data$PuzzAcc ~ data$atleastsrw2, paired = FALSE)
wilcox_effsize(data, PuzzAcc ~ atleastsrw2, paired = FALSE)
wilcox.test(data$RankAcc ~ data$GTD2, paired = FALSE)
wilcox_effsize(data, RankAcc ~ GTD2, paired = FALSE)
wilcox.test(data$PAAcc ~ data$atleastgf2, paired = FALSE)
wilcox_effsize(data, PAAcc ~ atleastgf2, paired = FALSE)
wilcox.test(data$PAAcc ~ data$feedback2, paired = FALSE)
wilcox_effsize(data, PAAcc ~ feedback2, paired = FALSE)

wilcox.test(data$PuzzAcc ~ data$best, paired = FALSE)
wilcox_effsize(data, PuzzAcc ~ best, paired = FALSE)
wilcox.test(data$PAAcc ~ data$best, paired = FALSE)
wilcox_effsize(data, PAAcc ~ best, paired = FALSE)
wilcox.test(data$PAAcc ~ data$feedback2, paired = FALSE)
wilcox_effsize(data, PAAcc ~ feedback2, paired = FALSE)


data <- read_csv("PuzzTask_Children.csv")

wilcox.test(data$avgPlan1, data$avgPlan2, paired = TRUE)
wilcox.test(data$avgSD1, data$avgSD2, paired = TRUE)
wilcox.test(data$RankDiff1, data$RankDiff2, paired = TRUE)
wilcox.test(data$Pred4Time, data$Pred9Time, paired = TRUE)
wilcox.test(data$AvgPredAcc1, data$AvgPredAcc2, paired = TRUE) 

boxplot(data$avgPlan1, data$avgPlan2)
boxplot(data$avgSD1, data$avgSD2)
boxplot(data$RankDiff1, data$RankDiff2)
boxplot(data$Pred4Time, data$Pred9Time)
boxplot(data$AvgPredAcc1, data$AvgPredAcc2)

gkgamma(mytable)
GKgamma(mytable)

mytable <- table(data$avgPlanall, data$PuzzAcc)
mytable <- table(data$avgSDall, data$PuzzAcc)
mytable <- table(data$SAT, data$PuzzAcc)
mytable <- table(data$PredDiff, data$PuzzAcc)
mytable <- table(data$RankDiffall, data$PuzzAcc)
mytable <- table(data$AvgPredAcc, data$PuzzAcc)
mytable <- table(data$CJPuzzles, data$PuzzAcc)
mytable <- table(data$CJTime, data$AvgPredAcc)
mytable <- table(data$RefTimeAcc, data$PuzzAcc)
gkgamma(mytable)

mytable <- table(data$avgPlanall, data$OrLit)
mytable <- table(data$avgPlanall, data$OrMath)
mytable <- table(data$avgSDall, data$OrLit)
mytable <- table(data$avgSDall, data$OrMath)
mytable <- table(data$SAT, data$OrLit)
mytable <- table(data$SAT, data$OrMath)
mytable <- table(data$RankDiffall, data$OrLit)
mytable <- table(data$RankDiffall, data$OrMath)
mytable <- table(data$AvgPredAcc, data$OrMath)
mytable <- table(data$AvgPredAcc, data$OrLit)
mytable <- table(data$RefPuzzAcc, data$OrLit)
mytable <- table(data$RefPuzzAcc, data$OrMath)
mytable <- table(data$RefTimeAcc, data$OrLit)
mytable <- table(data$RefTimeAcc, data$OrMath)
gkgamma(mytable)

mytable <- table(data$avgPlanall, data$avgSDall)
mytable <- table(data$avgPlanall, data$SAT)
mytable <- table(data$avgPlanall, data$RankDiffall)
mytable <- table(data$avgPlanall, data$AvgPredAcc)
mytable <- table(data$avgPlanall, data$RefTimeAcc)
mytable <- table(data$avgPlanall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$SAT)
mytable <- table(data$avgSDall, data$RankDiffall)
mytable <- table(data$avgSDall, data$AvgPredAcc)
mytable <- table(data$avgSDall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$RefTimeAcc)
mytable <- table(data$SAT, data$RankDiffall)
mytable <- table(data$SAT, data$AvgPredAcc)
mytable <- table(data$SAT, data$RefPuzzAcc)
mytable <- table(data$SAT, data$RefTimeAcc)
mytable <- table(data$RankDiffall, data$AvgPredAcc)
mytable <- table(data$RankDiffall, data$RefPuzzAcc)
mytable <- table(data$RankDiffall, data$RefTimeAcc)
mytable <- table(data$AvgPredAcc, data$RefPuzzAcc)
mytable <- table(data$AvgPredAcc, data$RefTimeAcc)
mytable <- table(data$RefPuzzAcc, data$RefTimeAccNoZ)
mytable <- table(data$avgPlan1, data$RankDiff1)
mytable <- table(data$avgPlan2, data$SAT)
mytable <- table(data$Age, data$avgSDall)
mytable <- table(data$Gender, data$avgSDall)
gkgamma(mytable)

ggscatter(data, x = "RefTimeAcc", y = "PuzzAcc", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Plan", ylab = "Achieve")

data <- read_csv("Qualitative_Children.csv")

wilcox.test(data$PuzzAcc ~ data$atleastrsw, paired = FALSE)
wilcox_effsize(data, PuzzAcc ~ atleastrsw, paired = FALSE)
wilcox.test(data$RankAcc ~ data$GTD, paired = FALSE)
wilcox_effsize(data, RankAcc ~ GTD, paired = FALSE)
wilcox.test(data$SAT ~ data$GTD, paired = FALSE)
wilcox_effsize(data, SAT ~ GTD, paired = FALSE)
wilcox.test(data$PAAcc ~ data$atleastgf, paired = FALSE)
wilcox_effsize(data, PAAcc ~ atleastgf, paired = FALSE) 
wilcox.test(data$PuzzAcc ~ data$feedback, paired = FALSE) 
wilcox_effsize(data, PuzzAcc ~ feedback, paired = FALSE) 
cor.test(data$StratNo, data$PuzzAcc, method = "spearman")
cor.test(data$StratNo, data$PAAcc, method = "spearman")
wilcox.test(data$PuzzAcc ~ data$atleastsrw2, paired = FALSE)
wilcox_effsize(data, PuzzAcc ~ atleastsrw2, paired = FALSE)
wilcox.test(data$RankAcc ~ data$GTD2, paired = FALSE)
wilcox_effsize(data, RankAcc ~ GTD2, paired = FALSE)
wilcox.test(data$PAAcc ~ data$atleastgf2, paired = FALSE)
wilcox_effsize(data, PAAcc ~ atleastgf2, paired = FALSE) 
wilcox.test(data$PAAcc ~ data$feedback2, paired = FALSE) 
wilcox_effsize(data, PAAcc ~ feedback2, paired = FALSE)

wilcox.test(data$PuzzAcc ~ data$best, paired = FALSE)
wilcox_effsize(data, PuzzAcc ~ best, paired = FALSE)
wilcox.test(data$PAAcc ~ data$best, paired = FALSE)
wilcox_effsize(data, PAAcc ~ best, paired = FALSE)

ceiling <- subset(data, Ceiling == "Y")
wilcox.test(ceiling$avgSD1, ceiling$avgSD2, paired = TRUE)
noceil <- subset(data, Ceiling == "N")
wilcox.test(noceil$avgSD1, noceil$avgSD2, paired = TRUE)
lowest <- subset(data, PuzzAcc < 13)
wilcox.test(lowest$avgSD1, lowest$avgSD2, paired = TRUE)
