install.packages("MESS")
install.packages("vcdExtra")
library(vcdExtra)
library(MESS)
library(readr)
library(stats)
library(ggpubr)
data <- read_csv("Time_Acc_Corr.csv")

mytable <- table(data$T18, data$R18)
gkgamma(mytable)
GKgamma(mytable)

mytable <- table(data$T1, data$R1)
mytable <- table(data$T2, data$R2)
mytable <- table(data$T3, data$R3)
mytable <- table(data$T4, data$R4)
mytable <- table(data$T5, data$R5)
mytable <- table(data$T6, data$R6)
mytable <- table(data$T7, data$R7)
mytable <- table(data$T8, data$R8)
mytable <- table(data$T9, data$R9)
mytable <- table(data$T10, data$R10)
mytable <- table(data$T11, data$R11)
mytable <- table(data$T12, data$R12)
mytable <- table(data$T13, data$R13)
mytable <- table(data$T14, data$R14)
mytable <- table(data$T15, data$R15)
mytable <- table(data$T16, data$R16)
mytable <- table(data$T17, data$R17)
mytable <- table(data$T18, data$R18)
mytable <- table(data$T19, data$R19)
mytable <- table(data$T20, data$R20)
mytable <- table(data$T21, data$R21)
mytable <- table(data$T22, data$R22)
mytable <- table(data$T23, data$R23)
mytable <- table(data$T24, data$R24)
mytable <- table(data$T25, data$R25)
mytable <- table(data$T26, data$R26)
mytable <- table(data$T27, data$R27)
mytable <- table(data$T28, data$R28)
mytable <- table(data$T29, data$R29)
mytable <- table(data$T30, data$R30)
mytable <- table(data$T31, data$R31)
mytable <- table(data$T32, data$R32)
mytable <- table(data$T33, data$R33)
mytable <- table(data$T34, data$R34)
mytable <- table(data$T35, data$R35)
mytable <- table(data$T36, data$R36)
mytable <- table(data$T37, data$R37)
mytable <- table(data$T38, data$R38)
mytable <- table(data$T39, data$R39)
mytable <- table(data$T40, data$R40)
mytable <- table(data$T41, data$R41)
mytable <- table(data$T42, data$R42)
mytable <- table(data$T43, data$R43)
mytable <- table(data$T44, data$R44)
mytable <- table(data$T45, data$R45)
mytable <- table(data$T46, data$R46)
mytable <- table(data$T47, data$R47)
mytable <- table(data$T48, data$R48)
mytable <- table(data$T49, data$R49)
mytable <- table(data$T50, data$R50)
mytable <- table(data$T51, data$R51)
mytable <- table(data$T52, data$R52)
mytable <- table(data$T53, data$R53)
mytable <- table(data$T54, data$R54)
mytable <- table(data$T55, data$R55)
mytable <- table(data$T56, data$R56)
mytable <- table(data$T57, data$R57)
mytable <- table(data$T58, data$R58)
mytable <- table(data$T59, data$R59)
mytable <- table(data$T60, data$R60)
mytable <- table(data$T61, data$R61)
mytable <- table(data$T62, data$R62)
mytable <- table(data$T63, data$R63)
mytable <- table(data$T64, data$R64)
mytable <- table(data$T65, data$R65)
mytable <- table(data$T66, data$R66)
mytable <- table(data$T67, data$R67)
mytable <- table(data$T68, data$R68)
mytable <- table(data$T69, data$R69)
mytable <- table(data$T70, data$R70)
mytable <- table(data$T71, data$R71)
mytable <- table(data$T72, data$R72)
mytable <- table(data$T73, data$R73)
mytable <- table(data$T74, data$R74)
mytable <- table(data$T75, data$R75)
mytable <- table(data$T76, data$R76)
mytable <- table(data$T77, data$R77)

library(metafor)
rma.mv(yi=Gamma, V=Error, data=data)
rma(ni=ni, ri=Gamma, measure="COR", data=data)

data <- read_csv("PuzzTaskResults_Adults_NoCeiling.csv")
mytable <- table(data$avgPlanall, data$PuzzAcc)
mytable <- table(data$avgSDall, data$PuzzAcc)
mytable <- table(data$SAT, data$PuzzAcc)
mytable <- table(data$PredDiff, data$PuzzAcc)
mytable <- table(data$RankDiffall, data$PuzzAcc)
mytable <- table(data$AvgPredAcc, data$PuzzAcc)
mytable <- table(data$CJPuzzles, data$PuzzAcc)
mytable <- table(data$CJTime, data$AvgPredAcc)
mytable <- table(data$RefTimeAcc, data$PuzzAcc)
gkgamma(mytable)
t.test(data$avgPlanall, data$avgPlanall2, paired = TRUE)
mytable <- table(data$avgPlanall, data$avgSDall)
mytable <- table(data$avgPlanall, data$SAT)
mytable <- table(data$avgPlanall, data$RankDiffall)
mytable <- table(data$avgPlanall, data$AvgPredAcc)
mytable <- table(data$avgPlanall, data$RefTimeAcc)
mytable <- table(data$avgPlanall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$SAT)
mytable <- table(data$avgSDall, data$RankDiffall)
mytable <- table(data$avgSDall, data$AvgPredAcc)
mytable <- table(data$avgSDall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$RefTimeAcc)
mytable <- table(data$SAT, data$RankDiffall)
mytable <- table(data$SAT, data$AvgPredAcc)
mytable <- table(data$SAT, data$RefPuzzAcc)
mytable <- table(data$SAT, data$RefTimeAcc)
mytable <- table(data$RankDiffall, data$AvgPredAcc)
mytable <- table(data$RankDiffall, data$RefPuzzAcc)
mytable <- table(data$RankDiffall, data$RefTimeAcc)
mytable <- table(data$AvgPredAcc, data$RefPuzzAcc)
mytable <- table(data$AvgPredAcc, data$RefTimeAcc)
mytable <- table(data$RefPuzzAcc, data$RefTimeAcc)
mytable <- table(data$avgPlan1, data$RankDiff1)
gkgamma(mytable)


ggscatter(data, x = "RefTimeAcc", y = "PuzzAcc", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Plan", ylab = "Achieve")
