install.packages("MESS")
install.packages("vcdExtra")
library(vcdExtra)
library(MESS)
library(readr)
library(stats)
library(ggpubr)

data <- read_csv("PuzzTask_Adults.csv")

wilcox.test(data$avgPlan1, data$avgPlan2, paired = TRUE)
wilcox.test(data$avgSD1, data$avgSD2, paired = TRUE)
wilcox.test(data$RankDiff1, data$RankDiff2, paired = TRUE)
wilcox.test(data$Pred4Time, data$Pred9Time, paired = TRUE)
wilcox.test(data$AvgPredAcc1, data$AvgPredAcc2, paired = TRUE)

gkgamma(mytable)
GKgamma(mytable)

mytable <- table(data$avgPlanall, data$PuzzAcc)
mytable <- table(data$avgSDall, data$PuzzAcc)
mytable <- table(data$SAT, data$PuzzAcc)
mytable <- table(data$PredDiff, data$PuzzAcc)
mytable <- table(data$RankDiffall, data$PuzzAcc)
mytable <- table(data$AvgPredAcc, data$PuzzAcc)
mytable <- table(data$CJPuzzles, data$PuzzAcc)
mytable <- table(data$CJTime, data$AvgPredAcc)
mytable <- table(data$RefTimeAcc, data$PuzzAcc)
gkgamma(mytable)

mytable <- table(data$avgPlanall, data$avgSDall)
mytable <- table(data$avgPlanall, data$SAT)
mytable <- table(data$avgPlanall, data$RankDiffall)
mytable <- table(data$avgPlanall, data$AvgPredAcc)
mytable <- table(data$avgPlanall, data$RefTimeAcc)
mytable <- table(data$avgPlanall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$SAT)
mytable <- table(data$avgSDall, data$RankDiffall)
mytable <- table(data$avgSDall, data$AvgPredAcc)
mytable <- table(data$avgSDall, data$RefPuzzAcc)
mytable <- table(data$avgSDall, data$RefTimeAcc)
mytable <- table(data$SAT, data$RankDiffall)
mytable <- table(data$SAT, data$AvgPredAcc)
mytable <- table(data$SAT, data$RefPuzzAcc)
mytable <- table(data$SAT, data$RefTimeAcc)
mytable <- table(data$RankDiffall, data$AvgPredAcc)
mytable <- table(data$RankDiffall, data$RefPuzzAcc)
mytable <- table(data$RankDiffall, data$RefTimeAcc)
mytable <- table(data$AvgPredAcc, data$RefPuzzAcc)
mytable <- table(data$AvgPredAcc, data$RefTimeAcc)
mytable <- table(data$RefPuzzAcc, data$RefTimeAcc)
mytable <- table(data$avgPlan1, data$RankDiff1)
gkgamma(mytable)

anova <- aov(avgPlanall ~ Ceiling, data = data)
anova <- aov(avgSDall ~ Ceiling, data = data)
anova <- aov(RefPuzzAcc ~ Ceiling, data = data)
summary(anova)
TukeyHSD(anova)

ggscatter(data, x = "RefTimeAcc", y = "PuzzAcc", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "spearman",
          xlab = "Plan", ylab = "Achieve")